version: '3.3'

services:
  elasticsearch:
    image: elastic8
    volumes:
      - elastic_data:/var/lib/elasticsearch
    ports:
      - "9200:9200"

  kibana:
    image: kibana8
    ports:
      - "5601:5601"

volumes:
  elastic_data:
